spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: MovieRecommendation

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    username: U
    password: P
